spring.application.name=pos-backend
spring.datasource.url=jdbc:mysql://localhost:3306/pos_system
spring.datasource.username=root

spring.datasource.password=Sipdiyamax@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true